export const INITIAL_APP_LOAD = "INITIAL_APP_LOAD";
export const SET_UPDATE_DATA = "SET_UPDATE_DATA";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_TOGGLE_DRAWER = "SET_TOGGLE_DRAWER";